### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by tfrodin** [FranklinChen/homebrew-tap#1]
I wish to use hugs on macOS. Are there any fixes for this issue or workarounds perhaps?

using brew to install as instructed [here](https://georgegarside.com/blog/macos/installing-hugs-98-haskell/)

`brew install FranklinChen/tap/hugs --HEAD`

```
==> ./configure --prefix=/usr/local/Cellar/hugs/HEAD-5cf7060
==> make
Last 15 lines from /Users/tho/Library/Logs/Homebrew/hugs/02.make:

runhugs: Error occurred
ERROR "libraries/bootlib/Foreign/Storable.hs":148 - Undefined type constructor "HTYPE_INT"


echo timestamp for bootlib >bootlib/.stamp
cd ../cpphs; HUGSFLAGS=-P../libraries/bootlib HUGSDIR=../hugsdir ../src/runhugs -98 ../packages/Cabal/examples/hapax.hs configure --verbose --hugs --prefix='/usr/local/Cellar/hugs/HEAD-5cf7060' --scratchdir='../hugsdir/packages/cpphs' --with-compiler=../src/ffihugs
runhugs: Error occurred
ERROR "../libraries/bootlib/Hugs/Storable.hs" - Error while importing DLL "../libraries/bootlib/Hugs/Storable.so":
dlopen(../libraries/bootlib/Hugs/Storable.so, 9): image not found



make[1]: *** [../hugsdir/programs/cpphs/Main.hs] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/franklinchen/homebrew-tap/issues
```

macOS 10.15.7

Homebrew 2.5.11
Homebrew/homebrew-core (git revision b21842; last commit 2020-11-20)
Homebrew/homebrew-cask (git revision e59e8; last commit 2020-11-20)

**Comment by FranklinChen** [comment]
Thanks for the report! I haven't built hugs for a while, so it appears that sometime in the last two years something in the Mac development toolkit changed. I'll investigate.

**Comment by FranklinChen** [comment]
This should work now.

**Comment by tfrodin** [comment]
> This should work now.

It did work. Thanks for fixing it so quickly!

**Comment by barracuda156** [comment]
> This should work now.

@FranklinChen Could you say what in particular fixes ` Undefined type constructor "HTYPE_INT"` error?
I am getting it on build bots: https://github.com/macports/macports-ports/runs/7734530076?check_suite_focus=true

Tried adding `configure.cflags-append -Wno-implicit-function-declaration` (for `gcc`), but it did not help:
https://github.com/macports/macports-ports/runs/7735451425?check_suite_focus=true
